### ISSUE TITLE
Add atomic values in API messages

### ISSUE THREAD

**Issue by regseb** [birjj/svglint#91]
## Actual

The JavaScript API returns `messages` with the following data:

```JavaScript
messages: [
  {
    message: 'Element disallowed\n  At node \x1B[1m<line>\x1B[22m (16:7)',
    type: 'error'
  }
]
```

Processing this data is complicated by the fact that the message property contains a lot of information and is adapted to be displayed in the console.

## Expected

The data would have to be extracted and returned in other properties:

```JavaScript
messages: [
  {
    message: 'Element disallowed\n  At node \x1B[1m<line>\x1B[22m (16:7)',
    type: 'error',
    reason: 'Element disallowed at node <line>',
    line: 16,
    column: 7
  }
]
```

## Extra information

I'm developing [Metalint](https://github.com/regseb/metalint), a tool that aggregates the results of several linters. I'd like to integrate SVGLint, but I can't convert SVGLint results into a Metalint specific format.

Here's an example of how I convert HTMLHint results: [`metalint/src/core/wrapper/htmlhint.js`](https://github.com/regseb/metalint/blob/61b81d7/src/core/wrapper/htmlhint.js#L65-L81)

**Comment by ericcornelissen** [comment]
Thanks for the request, this seems like a reasonable thing to do. I think it's indeed important to keep the `message` and `type` unchanged to avoid breaking changes, but adding new values should be fine.

I'm too out of touch with this project to say how hard/easy this would be to achieve - in particular I'm unsure how this change would play with custom rules. In any case, I'd be happy to have a look at a Pull Request if you want to make a contribution (otherwise this project is somewhat dormant so you might not see this being implemented for a while...).

---

### Off topic

> I'm developing [Metalint](https://github.com/regseb/metalint), a tool that aggregates the results of several linters. I'd like to integrate SVGLint, but I can't convert SVGLint results into a Metalint specific format.

Cool project :wink: For the `package.json` linting I'd suggest considering [`publint`](https://www.npmjs.com/package/publint) and [`arethetypeswrong`](https://www.npmjs.com/package/@arethetypeswrong/cli). I also wonder what you'd think of including tools like [`type-coverage`](https://www.npmjs.com/package/type-coverage) or [`licensee`](https://www.npmjs.com/package/licensee) with it, as they're not conventional linters but could be useful. In any case.
